spring:
  datasource:
    url: jdbc:mysql://localhost:3302/bt_upload
    username: root
    password: 1312
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  privateKey: or2hPA3SNB4crQn6ljU+8AADpAFQW3ntLzHTQKum9gc=
uploads:
  path: C:\TEDDY\CyberSoft\Java20\Program\Java20-Baitap-UploadFile-090323\image